"""Add Example model

Revision ID: 3e7e2427717e
Revises: 2a7c12f2152c
Create Date: 2025-06-14 16:52:10.113843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e7e2427717e'
down_revision = '2a7c12f2152c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('korean', sa.String(length=255), nullable=False),
    sa.Column('vietnamese', sa.String(length=255), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_column('note')

    op.drop_table('example')
    # ### end Alembic commands ###
