"""recreate word table

Revision ID: 2a7c12f2152c
Revises: b21f618fbedd
Create Date: 2025-06-14 16:17:03.898569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a7c12f2152c'
down_revision = 'b21f618fbedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('korean', sa.String(length=100), nullable=False),
    sa.Column('vietnamese', sa.String(length=100), nullable=False),
    sa.Column('pos', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    # ### end Alembic commands ###
